/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableOverviewRouteImport } from './routes/tableOverview'
import { Route as CandleSticksRouteImport } from './routes/candleSticks'
import { Route as IndexRouteImport } from './routes/index'

const TableOverviewRoute = TableOverviewRouteImport.update({
  id: '/tableOverview',
  path: '/tableOverview',
  getParentRoute: () => rootRouteImport,
} as any)
const CandleSticksRoute = CandleSticksRouteImport.update({
  id: '/candleSticks',
  path: '/candleSticks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candleSticks': typeof CandleSticksRoute
  '/tableOverview': typeof TableOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candleSticks': typeof CandleSticksRoute
  '/tableOverview': typeof TableOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candleSticks': typeof CandleSticksRoute
  '/tableOverview': typeof TableOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candleSticks' | '/tableOverview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candleSticks' | '/tableOverview'
  id: '__root__' | '/' | '/candleSticks' | '/tableOverview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandleSticksRoute: typeof CandleSticksRoute
  TableOverviewRoute: typeof TableOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tableOverview': {
      id: '/tableOverview'
      path: '/tableOverview'
      fullPath: '/tableOverview'
      preLoaderRoute: typeof TableOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candleSticks': {
      id: '/candleSticks'
      path: '/candleSticks'
      fullPath: '/candleSticks'
      preLoaderRoute: typeof CandleSticksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandleSticksRoute: CandleSticksRoute,
  TableOverviewRoute: TableOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
